package model;

public enum TransactionStatus {
    AUTORIZACAO_CARTAO_PROCESSADA,
    AUTORIZACAO_CARTAO_REJEITADA,
    EFETIVACAO_PROCESSADA,
    EFETIVACAO_REJEITADA,
    ORQUESTRACAO_FINALIZADA,
    ORQUESTRACAO_ERRO

}
